language: python
python:
    - "2.7"
before_install:
  - cd package

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
    - python setup.py develop
    - nosetests --with-coverage --cover-package=cloudshell

after_success:
- coveralls